CREATE TABLE IF NOT EXISTS distributor (
  distributorID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  distributorName VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS card (
  cardID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  cardName VARCHAR(32) NOT NULL,
  cardDescription VARCHAR(128) NOT NULL,
  cardArt VARCHAR(32) NOT NULL,
  distributorID CHAR(8) NOT NULL,
  FOREIGN KEY (distributorID) REFERENCES distributor(distributorID)
);

CREATE TABLE IF NOT EXISTS deck (
  deckID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  deckName VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS cardDeckLink (
  cardID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  deckID INTEGER NOT NULL,
  FOREIGN KEY (cardID) REFERENCES card(cardID),
  FOREIGN KEY (deckID) REFERENCES deck(deckID)
);


